import { Inter } from "next/font/google";
import "./globals.css";
import { NavbarComponent } from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kowy Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="md:flex w-full h-screen">
        <NavbarComponent/>
        <div className="w-full overflow-y-auto">
          {children}
        </div>
      </div>
      </body>
    </html>
  );
}
