import "./globals.css";
import { NavbarComponent } from "@/components/navbar";

export const metadata = {
  title: "Kowy Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
    <body className="h-screen overflow-hidden">
      <div className="md:flex w-full h-full bg-gray-100">
        <NavbarComponent />
        <div className="w-full overflow-y-auto">
          {children}
        </div>
      </div>
    </body>
  </html>
  );
}
