export const URL = import.meta.env.VITE_URL || 'http://localhost:3001/api/'
export const Provinces = [  "buenos aires",  
                            "catamarca",  
                            "chaco",  
                            "chubut",  
                            "córdoba",  
                            "corrientes",  
                            "entre ríos",  
                            "formosa",  
                            "jujuy",  
                            "la pampa",  
                            "la rioja",  
                            "mendoza",  
                            "misiones",  
                            "neuquén",  
                            "río negro",  
                            "salta",  
                            "san juan",  
                            "san luis",  
                            "santa cruz",  
                            "santa fe",  
                            "santiago del estero",  
                            "tierra del fuego",  
                            "tucumán"]
